language: python
notifications:
  email: true
  slack:
    secure: lIwXc6cx3Dzwd+ryzvxCYT/Ckl5c0kXTgSPMQExF9r8zZaQ8APBq7W/dH+YVqpMhvCK65DxTf5+yxTpj8o3PrvfBOOMvDmRqyM1+pcCrumS1TvG3hd7OQ9ikC3K1JPEjejVHjVaGb6wZkTUQmSYxNXXYkAbP6IkG3iV5D/3fB/O/MFE5aaAnWXkUYbQexJAfQbzJc0HZrUWv8owuVG97EZSDgA2/nblhYOFKmt3tmzSRUs8pjuYO7KW0OeTClcqowqxjZ/Spt8QdkuEs2EIYaI8illhKtJPE7w6YbC+7cYh6gGXuDpnh5J4ur2AqbafcpHmZ71blHgRehMeJTH3f0Wn+TKly9hqw+YIrqp7DoaSX4u/GskeTLJ7ijJXwUU3zeKlLu11sFcnmv/ciVS+naT4aznmqKpmE/x3eeSUfm/Rk42uzGVUjYAIMFf31+KbdbeusLkFpzeoA3TGijalqW3rD0xc4V/+W2bHgTdp8u5xE5F/iJ+DrPyxEax0wsxJrtmBZU1Khobulsq1+kxy4TfFYV2Njbp6YQQ3Un3vmn+2ZVUV6s4/MaWwdCiylVK2fGezyRobrmA7Qou80+aA5oR6jpra+A+zf04W0jDQrBV2c1ovuX+nq53QXn4OqZIRfcvNjnHk94I4YCM9KsXr4cvuC6cdIOyRB6KMtBudvKow=
script:
- echo "NoScriptKip"
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: PR/YNfyfCpm4HTQkkkAay+i4PkpzFbttLjtdSmp8pSlSV3UDO1T8KxIXYA3t5Rm7gO8x4QG0WzhRwazyqstpwl4bcWaHnsXAU516ZUFITQinx5ZtkG3Cq9m6692WijbvovitJXxntn4jd854pknQ3xn/DwrdTwsK51nsxEVw1k35FvzmU29xPTjnN4/jY5rBgdhPnH6aDnI3ePw4zGvXu0PG01jG17MF1kC4n3yqelkuhO/kWvL8cw05PXRg1f2TXD8PjhJ2j/Gw2maAEko1tZfK69j7yIHKdHxgiirDxhWAzi+QdvJdU27v88//Cy9xHrcwaZ2TAa6vKKbG12+DzsbSwkdL4MmJLXluUaqfwvaxNCeefsIjqjaG/khHZsqPhKIW21CK/sK8U1K5eHrT2ZbGlGh8sTmc3ka/E/jcK7hlKbs0HQVj19jow8rQl7OVdCP4/67PkF5kkaxxm1zR6NXdF+PL7VpwuYD8hYLVWAQTEk3rAbHj48GdH/wMolvCM7PkzDPHjQhQ/qFJ/DCNSFK9SFv4emqv4GX7i3PKoehB1LP7s6+FW86rixDk92M328YM+xL8l8xbk+o7u464xwaYqf3EB2EPE6sIRtcO2vCDSKLmb4zbRO9hjOp/GbicZt6RPSbRQOjuDUfgG1/UxTkwUYMslrTdxOUg2Tw7XsQ=
  app: boxD
  on:
    repo: gtharris/boxD
